const signin = require('express').Router()
const clientModel = require('../models/client.model');
const bcrypt = require('bcrypt');
const { sign } = require('jsonwebtoken');
signin.get('/signin',(req,res)=>{
    res.render('signin.ejs',{errors:[],oldInputs:{}})
})
signin.post('/handleSignIn',async(req,res)=>{
    const {email , password} = req.body
    let client = await clientModel.findOne({email:email.toLowerCase()})
    if(client){
        const match = await bcrypt.compare(password, client.password); 
        if(match){
            res.redirect(`/home/${client._id}`);
        }
        else{
            res.render('signin.ejs' ,{errors: [{ param: 'password Incorrect' }],oldInputs:{email , password}})
        }
    }
    else{
        res.render('signin.ejs' ,{errors: [{ param: 'email Incorrect' }],oldInputs:{email , password}})
    }
})
signin.get('/logout',(req,res)=>{
    res.redirect('/signin')
})
signin.get('/home/contact-us',(req,res)=>{
    res.render('contact-us.ejs')
})
signin.get('/home/clubs',(req,res)=>{
    res.render('clubs.ejs')
})
signin.get('/home/clubs/alahly',(req,res)=>{
    res.render('alahly.ejs')
})
signin.get('/home/blog',(req,res)=>{
    res.render('blog.ejs')
})
signin.get('/home/blog-advice',(req,res)=>{
    res.render('blog-advice.ejs')
})
signin.get('/home/blog-advice2',(req,res)=>{
    res.render('blog-advice2.ejs')
})
signin.get('/home/blog-advice3',(req,res)=>{
    res.render('blog-advice3.ejs')
})
signin.get('/home/alahly-buy',(req,res)=>{
    res.render('alahly-buy.ejs')
})
signin.get('/home/alasma3ily-buy',(req,res)=>{
    res.render('alasma3ily-buy.ejs')
})
signin.get('/home/almuqawlun-buy',(req,res)=>{
    res.render('almuqawlun-buy.ejs')
})
signin.get('/home/pyramids-buy',(req,res)=>{
    res.render('pyramids-buy.ejs')
})
signin.get('/home/clubs/Barca',(req,res)=>{
    res.render('barcelona.ejs')
})
signin.get('/home/clubs/Barca/barcelona-product',(req,res)=>{
    res.render('barcelona-product.ejs')
})
signin.get('/home/clubs/juve',(req,res)=>{
    res.render('juve.ejs')
})
signin.get('/home/clubs/juve/juve-product',(req,res)=>{
    res.render('juve-product.ejs')
})
signin.get('/home/clubs/bayern',(req,res)=>{
    res.render('bayern.ejs');
})
signin.get('/home/clubs/bayern/bayern-product',(req,res)=>{
    res.render('bayern-product.ejs');
})
signin.get('/home/paris-buy',(req,res)=>{
    res.render('baris-buy.ejs')
})
signin.get('/home/barcelona-buy',(req,res)=>{
    res.render('barcelona-buy.ejs')
})
signin.get('/home/juve-buy',(req,res)=>{
    res.render('juve-buy.ejs');
})
signin.get('/home/real-buy',(req,res)=>{
    res.render('real-buy.ejs')
})
signin.get('/home/brands/umbro',(req,res)=>{
    res.render('umbro.ejs')
})
signin.get('/home/brands/new-balance',(req,res)=>{
    res.render('new-balance.ejs')
})
signin.get('/home/barnds/adidas',(req,res)=>{
    res.render('adidas.ejs')
})
signin.get('/home/brands/nike',(req,res)=>{
    res.render('nike.ejs')
})
module.exports=signin;